By Paritosh Sanadhya(Member of Team Swarm Robotics)
marsiitr/Swarm_Robotics pull request #2
Opened 2020-07-28 06:26 UTC by Pasa1912

2020-07-28 09:57 UTC, annushree21 commented
Few changes are needed.
1. Put Report and poster into single folder.
2. Team names and mentors name should be hyperlinked to their git profile.
3. Add at least one photo each in mechanical aspect and electronic aspect of readme file.

2020-07-28 10:04 UTC, SanjeevKrishnan requested changes
@Pasa1912 Changes are required!
1. Poster and Report have to be present inside a folder named "Poster and Report".
2. Poster has to be in .jpg format. 
3. Poster is not up to the mark. Make sure that you have "Models and Robotics Section", "Srishti 2020", Project Abstract, a picture related to your project in your poster.
4. In Report, maintain uniformity among headings and sub-headings.
5. In Report, Applications has to be written after Cost Structure. Also, add Limitations and Reference at the end.
6. "Shapes" should not be present in the root directory. It can be placed inside Images and Videos/Images. But make sure that shapes are in .jpg format, not .ppt format.
7. CAD Images have to be present inside Mechanical Design folder, not inside Images and Videos/Images.
8. In README.md, Mechanical Aspect, and Electronics Aspect is not about components used in mechanical and electronics design. You should explain mechanical and electronics features of your project under that sub-heading in short and crisp way. You should have separate sub-heading named "Components Used" to list out your components. 
9. In README.md, hyperlink Team Members and Mentors names with their GitHub profile link.
10. In README.md, justify the text using HTML tags.

2020-07-28 13:48 UTC, SanjeevKrishnan requested changes
@Pasa1912 Also try not to use images obtained from internet!

2020-07-28 13:50 UTC, Pasa1912 commented
> @Pasa1912 Also try not to use images obtained from internet!

Sir, we don't have enough images of our project.

2020-07-28 14:07 UTC, SanjeevKrishnan commented
> @SanjeevKrishnan Sir, we don't have enough images of our project.
@Pasa1912 You can use full view CAD Images

2020-07-28 14:26 UTC, Shubhanshu07 commented
@Pasa1912 
1. Write content of readme normal not in italics.
2. Do not use any internet photo.
3. Write team members and mentors as ordered list not unorders list.
4. Add solid works jped in readme also.
5. For video you can upload bot recognition video using shapes and all.
6. Flow chart is missing.

2020-07-29 13:49 UTC, SanjeevKrishnan requested changes
@Pasa1912 Very minor Changes
1. Use `<p align="justify">Content<\p>` to justify text in README.md where Content is the text you want to justify.

2020-07-29 13:49 UTC, SanjeevKrishnan commented on README.md
> +## Cost Structure of the Components Used
Make this "Cost Structure" instead of "Cost Structure of the Components Used"

2020-07-29 13:49 UTC, SanjeevKrishnan commented on README.md
> +## Working
Move Working above Mechanical Aspect

2020-07-29 14:24 UTC, SanjeevKrishnan commented on README.md
> +<p align ="justify">
@Pasa1912 Remove this `<p>` tag. Use this tag separately for individual paragraphs which you want to justify

2020-07-29 14:36 UTC, SanjeevKrishnan approved these changes
@Pasa1912 Great Work!
@Shubhanshu07 I suggest for merge

2020-07-29 14:41 UTC, Shubhanshu07 commented
@Pasa1912 Looks good to  me

2020-07-29 14:41 UTC, merged